### ISSUE TITLE
Filtering out *png files!

### ISSUE THREAD

**Issue by VarunBatraIT** [zevilz/zImageOptimizer#4]
I have written a blog post and readers have a major concerns about PNG files, they want it to be filtered - that means compress on jpeg files, if there is any provision in this bash? 

Here is the link if you care - [Lossless Image Compressions using Docker](https://webapplicationconsultant.com/docker/lossless-image-compressions-using-docker/)

**Comment by zevilz** [comment]
I can't access this page. They want compress only JPEGs excluding PNGs?

**Comment by VarunBatraIT** [comment]
Hi, Yes! 

You should be able to visit the page now. 

Here are some comments:

```
The time and server cost it took didn’t justify the worth. If there is any way I can filter pngs?
```

```
After few minutes it passed to next image sorry.
```

**Comment by zevilz** [comment]
At this time, it is impossible to disable png optimization, but you can remove utilities for optimizing png (pngcrush, optipng, pngout, advpng), then the script will skip optimizing them.

Now I'm working on script refactoring for support extensions. Using them you can change logic of the script, including filtering image types.

**Comment by zevilz** [comment]
@VarunBatraIT now you can use [disable_png extension](https://github.com/zevilz/zImageOptimizer-extensions/blob/master/disable_png)
