### ISSUE TITLE
cannot optimized

### ISSUE THREAD

**Issue by congthanhsem** [zevilz/zImageOptimizer#8]
sudo bash zImageOptimizer.sh -p /home/pi/xulyanh/ 

Optimizing...
[1/1] /home/pi/xulyanh/799795.jpg... stat: cannot read file system information for '%Lp': No such file or directory
chmod: invalid mode: ‘File:’
Try 'chmod --help' for more information.
[NOT OPTIMIZED] 984.9Kb

**Comment by zevilz** [comment]
What operating system are you running the script on?
