### ISSUE TITLE
Feature: use xattrs to tag "optimised" files?

### ISSUE THREAD

**Issue by VADemon** [zevilz/zImageOptimizer#9]
> After optimization is finished, the script deletes this file (or deletes current path to working directory from the file with several parallel optimizations). This is done to prevent cycling optimization and avoid conflicts during optimization for longer than period between optimizations.

There was a lot of thought put into working around re-optimising previously processed files.

I think xattrs pose a good solution to mark the files once processes to not be touched again. What do you think?

**Comment by zevilz** [comment]
Time markers are more cross-platform and do not depend on the file system. It is also easy to change the marker change time and not optimize new images already optimized by other utilities. But I will think about it.
